import type { Metadata } from "next";
import "./globals.css";
import { Orbitron } from "next/font/google";
import AppCheckInit from "@/components/AppCheckInit";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-orbitron",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${orbitron.variable}`}>
      <body>
        <AppCheckInit />
        {children}
      </body>
    </html>
  );
}
